import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/contexts/AuthContext";
import { CartProvider } from "@/contexts/CartContext";
import Navbar from "@/app/_components/Navbar";
import { User, UserRole } from "@/types/user";
import { cookies } from "next/headers";

import { URL } from "node:url";

export function getBaseUrl(envUrl?: string): string {
  const baseUrl = envUrl ?? "http://localhost";

  try {
    new URL(baseUrl);
    return baseUrl;
  } catch (err) {
    console.error("Invalid BASE_URL provided, falling back to localhost:", err);
    return "http://localhost";
  }
}

const internalBaseUrl = getBaseUrl(process.env.INTERNAL_BASE_URL);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type AuthInfo = {
  accessToken: string | null;
  accessRole: UserRole | null;
  user?: User;
};

async function fetchAuth(): Promise<AuthInfo | null> {
  const cookie = await cookies();

  if (!cookie.has("refresh_token")) return null;

  const res = await fetch(internalBaseUrl + "/api/auth/refresh", {
    method: "POST",
    headers: {
      Cookie: cookie.toString(),
    },
    cache: "no-store",
  });

  if (!res.ok) {
    return null;
  }

  const authData = await res.json();

  const meRes = await fetch(internalBaseUrl + "/api/user/me", {
    method: "GET",
    headers: {
      Authorization: "Bearer " + authData.accessToken,
    },
    cache: "no-store",
  });

  if (!res.ok) {
    return null;
  }

  const me = await meRes.json();

  return {
    accessToken: authData.accessToken,
    accessRole: authData.profile,
    user: me.data,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await fetchAuth();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider auth={auth}>
          <CartProvider>
            <Navbar />
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
