import { Product, Shop, User, ProductReview, ShopReview } from '@/types';

// Mock Users
export const mockUsers: User[] = [
    { id: 1, name: 'John Doe', email: 'john@example.com' },
    { id: 2, name: 'Jane Smith', email: 'jane@example.com' },
    { id: 3, name: 'Bob Johnson', email: 'bob@example.com' },
    { id: 4, name: 'Alice Williams', email: 'alice@example.com' },
    { id: 5, name: 'Charlie Brown', email: 'charlie@example.com' },
];

// Current logged-in user (for testing)
export const currentUser = mockUsers[0];

// Mock Shops
export const mockShops: Shop[] = [
    {
        id: 1,
        name: 'Tech Paradise',
        description: 'Your one-stop shop for all tech gadgets',
        image: 'https://via.placeholder.com/400x300/3B82F6/FFFFFF?text=Tech+Paradise',
        ownerName: 'Michael Tech',
    },
    {
        id: 2,
        name: 'Fashion Hub',
        description: 'Trendy clothes and accessories',
        image: 'https://via.placeholder.com/400x300/EC4899/FFFFFF?text=Fashion+Hub',
        ownerName: 'Sarah Style',
    },
    {
        id: 3,
        name: 'Home Essentials',
        description: 'Everything you need for your home',
        image: 'https://via.placeholder.com/400x300/10B981/FFFFFF?text=Home+Essentials',
        ownerName: 'David Home',
    },
];

// Mock Products
export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'Wireless Headphones',
        description: 'Premium noise-canceling wireless headphones with 30-hour battery life',
        price: 199.99,
        image: 'https://via.placeholder.com/300/3B82F6/FFFFFF?text=Headphones',
        shopId: 1,
        shopName: 'Tech Paradise',
    },
    {
        id: 2,
        name: 'Smart Watch',
        description: 'Fitness tracking smart watch with heart rate monitor',
        price: 299.99,
        image: 'https://via.placeholder.com/300/8B5CF6/FFFFFF?text=Smart+Watch',
        shopId: 1,
        shopName: 'Tech Paradise',
    },
    {
        id: 3,
        name: 'Designer Handbag',
        description: 'Elegant leather handbag perfect for any occasion',
        price: 159.99,
        image: 'https://via.placeholder.com/300/EC4899/FFFFFF?text=Handbag',
        shopId: 2,
        shopName: 'Fashion Hub',
    },
    {
        id: 4,
        name: 'Running Shoes',
        description: 'Comfortable running shoes with advanced cushioning',
        price: 129.99,
        image: 'https://via.placeholder.com/300/F59E0B/FFFFFF?text=Shoes',
        shopId: 2,
        shopName: 'Fashion Hub',
    },
    {
        id: 5,
        name: 'Coffee Maker',
        description: 'Programmable coffee maker with built-in grinder',
        price: 89.99,
        image: 'https://via.placeholder.com/300/10B981/FFFFFF?text=Coffee+Maker',
        shopId: 3,
        shopName: 'Home Essentials',
    },
    {
        id: 6,
        name: 'Air Purifier',
        description: 'HEPA filter air purifier for clean and fresh air',
        price: 179.99,
        image: 'https://via.placeholder.com/300/06B6D4/FFFFFF?text=Air+Purifier',
        shopId: 3,
        shopName: 'Home Essentials',
    },
];

// Mock Product Reviews
export const mockProductReviews: ProductReview[] = [
    {
        id: 1,
        userId: 2,
        userName: 'Jane Smith',
        productId: 1,
        productName: 'Wireless Headphones',
        orderId: 1,
        rating: 4.5,
        productQualityRating: 5,
        deliveryTimeRating: 4,
        comment: 'Amazing sound quality! The noise cancellation is top-notch. Delivery was pretty fast too.',
        status: 'APPROVED',
        createdAt: '2026-01-20T10:30:00',
        updatedAt: '2026-01-20T10:30:00',
    },
    {
        id: 2,
        userId: 3,
        userName: 'Bob Johnson',
        productId: 1,
        productName: 'Wireless Headphones',
        orderId: 2,
        rating: 5.0,
        productQualityRating: 5,
        deliveryTimeRating: 5,
        comment: 'Best headphones I\'ve ever owned! Worth every penny. Lightning fast delivery!',
        status: 'APPROVED',
        createdAt: '2026-01-19T14:20:00',
        updatedAt: '2026-01-19T14:20:00',
    },
    {
        id: 3,
        userId: 4,
        userName: 'Alice Williams',
        productId: 1,
        productName: 'Wireless Headphones',
        orderId: 3,
        rating: 4.0,
        productQualityRating: 4,
        deliveryTimeRating: 4,
        comment: 'Great product overall. Battery life is impressive. Could be more comfortable for long sessions.',
        status: 'APPROVED',
        createdAt: '2026-01-18T09:15:00',
        updatedAt: '2026-01-18T09:15:00',
    },
    {
        id: 4,
        userId: 5,
        userName: 'Charlie Brown',
        productId: 2,
        productName: 'Smart Watch',
        orderId: 4,
        rating: 4.5,
        productQualityRating: 5,
        deliveryTimeRating: 4,
        comment: 'Love the fitness tracking features! Heart rate monitor is very accurate.',
        status: 'APPROVED',
        createdAt: '2026-01-17T16:45:00',
        updatedAt: '2026-01-17T16:45:00',
    },
    {
        id: 5,
        userId: 2,
        userName: 'Jane Smith',
        productId: 3,
        productName: 'Designer Handbag',
        orderId: 5,
        rating: 5.0,
        productQualityRating: 5,
        deliveryTimeRating: 5,
        comment: 'Absolutely gorgeous! The leather quality is exceptional. Arrived perfectly packaged.',
        status: 'APPROVED',
        createdAt: '2026-01-16T11:30:00',
        updatedAt: '2026-01-16T11:30:00',
    },
    {
        id: 6,
        userId: 1,
        userName: 'John Doe',
        productId: 5,
        productName: 'Coffee Maker',
        orderId: 6,
        rating: 4.5,
        productQualityRating: 5,
        deliveryTimeRating: 4,
        comment: 'Makes excellent coffee! The built-in grinder is a game changer.',
        status: 'APPROVED',
        createdAt: '2026-01-15T08:00:00',
        updatedAt: '2026-01-15T08:00:00',
    },
    {
        id: 7,
        userId: 3,
        userName: 'Bob Johnson',
        productId: 6,
        productName: 'Air Purifier',
        orderId: 7,
        rating: 3.5,
        productQualityRating: 4,
        deliveryTimeRating: 3,
        comment: 'Works well but delivery took longer than expected. Air quality has improved though.',
        status: 'APPROVED',
        createdAt: '2026-01-14T13:20:00',
        updatedAt: '2026-01-14T13:20:00',
    },
    {
        id: 8,
        userId: 4,
        userName: 'Alice Williams',
        productId: 4,
        productName: 'Running Shoes',
        orderId: 8,
        rating: 2.0,
        productQualityRating: 2,
        deliveryTimeRating: 2,
        comment: 'Size runs small and took forever to arrive. Material feels cheap.',
        status: 'PENDING',
        createdAt: '2026-01-22T10:00:00',
        updatedAt: '2026-01-22T10:00:00',
    },
];

// Mock Shop Reviews
export const mockShopReviews: ShopReview[] = [
    {
        id: 1,
        userId: 2,
        userName: 'Jane Smith',
        shopId: 1,
        shopName: 'Tech Paradise',
        orderId: 1,
        rating: 5.0,
        ownerInteractionRating: 5,
        shopQualityRating: 5,
        deliveryTimeRating: 4,
        comment: 'Excellent shop! Owner is very responsive and helpful. Great product selection.',
        status: 'APPROVED',
        createdAt: '2026-01-20T11:00:00',
        updatedAt: '2026-01-20T11:00:00',
    },
    {
        id: 2,
        userId: 3,
        userName: 'Bob Johnson',
        shopId: 1,
        shopName: 'Tech Paradise',
        orderId: 2,
        rating: 4.5,
        ownerInteractionRating: 5,
        shopQualityRating: 4,
        deliveryTimeRating: 5,
        comment: 'Fast shipping and great customer service. Will definitely shop here again!',
        status: 'APPROVED',
        createdAt: '2026-01-19T15:00:00',
        updatedAt: '2026-01-19T15:00:00',
    },
    {
        id: 3,
        userId: 2,
        userName: 'Jane Smith',
        shopId: 2,
        shopName: 'Fashion Hub',
        orderId: 5,
        rating: 5.0,
        ownerInteractionRating: 5,
        shopQualityRating: 5,
        deliveryTimeRating: 5,
        comment: 'Amazing fashion store! Owner has great taste and provides excellent recommendations.',
        status: 'APPROVED',
        createdAt: '2026-01-16T12:00:00',
        updatedAt: '2026-01-16T12:00:00',
    },
    {
        id: 4,
        userId: 1,
        userName: 'John Doe',
        shopId: 3,
        shopName: 'Home Essentials',
        orderId: 6,
        rating: 4.0,
        ownerInteractionRating: 4,
        shopQualityRating: 4,
        deliveryTimeRating: 4,
        comment: 'Good shop with quality home products. Professional service.',
        status: 'APPROVED',
        createdAt: '2026-01-15T09:00:00',
        updatedAt: '2026-01-15T09:00:00',
    },
    {
        id: 5,
        userId: 5,
        userName: 'Charlie Brown',
        shopId: 1,
        shopName: 'Tech Paradise',
        orderId: 4,
        rating: 3.0,
        ownerInteractionRating: 3,
        shopQualityRating: 3,
        deliveryTimeRating: 3,
        comment: 'Average experience. Products are good but customer service could be better.',
        status: 'PENDING',
        createdAt: '2026-01-22T11:00:00',
        updatedAt: '2026-01-22T11:00:00',
    },
];
